baseURL = 'https://www.carolduartemua.com.br'
languageCode = 'pt-br'
title = 'Carol Duarte'
theme = 'oludo'
enableRobotsTXT = true

[params]
Pixel = "1123025685120528"
GTags = ['G-TJD5QGBQ70']

# [menu]
#   [[menu.main]]
#     identifier = ''
#     name = 'Home'
#     url = '/'
#     weight = -200
    
#   [[menu.main]]
#     identifier = 'contacts'
#     name = 'Contatos'
#     url = '#contacts'
#     weight = -110
    